# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gRPCSampleData_pb2 as gRPCSampleData__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SamplePointsServerStub(object):
    """
    Define the Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.All_Sample_points = channel.unary_unary(
                '/sample_points.SamplePointsServer/All_Sample_points',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=gRPCSampleData__pb2.GetAll_Sample_pointsResp.FromString,
                )


class SamplePointsServerServicer(object):
    """
    Define the Service
    """

    def All_Sample_points(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SamplePointsServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'All_Sample_points': grpc.unary_unary_rpc_method_handler(
                    servicer.All_Sample_points,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=gRPCSampleData__pb2.GetAll_Sample_pointsResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sample_points.SamplePointsServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SamplePointsServer(object):
    """
    Define the Service
    """

    @staticmethod
    def All_Sample_points(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_points.SamplePointsServer/All_Sample_points',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            gRPCSampleData__pb2.GetAll_Sample_pointsResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
