# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPCSampleData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gRPCSampleData.proto',
  package='sample_points',
  syntax='proto3',
  serialized_options=b'\n\007ex.grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14gRPCSampleData.proto\x12\rsample_points\x1a\x1bgoogle/protobuf/empty.proto\".\n\nDMG_coords\x12\x0f\n\x07lat_deg\x18\x01 \x01(\x01\x12\x0f\n\x07lon_deg\x18\x02 \x01(\x01\"E\n\x18GetAll_Sample_pointsResp\x12)\n\x06points\x18\x01 \x03(\x0b\x32\x19.sample_points.DMG_coords2l\n\x12SamplePointsServer\x12V\n\x11\x41ll_Sample_points\x12\x16.google.protobuf.Empty\x1a\'.sample_points.GetAll_Sample_pointsResp\"\x00\x42\t\n\x07\x65x.grpcb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_DMG_COORDS = _descriptor.Descriptor(
  name='DMG_coords',
  full_name='sample_points.DMG_coords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat_deg', full_name='sample_points.DMG_coords.lat_deg', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lon_deg', full_name='sample_points.DMG_coords.lon_deg', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=114,
)


_GETALL_SAMPLE_POINTSRESP = _descriptor.Descriptor(
  name='GetAll_Sample_pointsResp',
  full_name='sample_points.GetAll_Sample_pointsResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='sample_points.GetAll_Sample_pointsResp.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=185,
)

_GETALL_SAMPLE_POINTSRESP.fields_by_name['points'].message_type = _DMG_COORDS
DESCRIPTOR.message_types_by_name['DMG_coords'] = _DMG_COORDS
DESCRIPTOR.message_types_by_name['GetAll_Sample_pointsResp'] = _GETALL_SAMPLE_POINTSRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DMG_coords = _reflection.GeneratedProtocolMessageType('DMG_coords', (_message.Message,), {
  'DESCRIPTOR' : _DMG_COORDS,
  '__module__' : 'gRPCSampleData_pb2'
  # @@protoc_insertion_point(class_scope:sample_points.DMG_coords)
  })
_sym_db.RegisterMessage(DMG_coords)

GetAll_Sample_pointsResp = _reflection.GeneratedProtocolMessageType('GetAll_Sample_pointsResp', (_message.Message,), {
  'DESCRIPTOR' : _GETALL_SAMPLE_POINTSRESP,
  '__module__' : 'gRPCSampleData_pb2'
  # @@protoc_insertion_point(class_scope:sample_points.GetAll_Sample_pointsResp)
  })
_sym_db.RegisterMessage(GetAll_Sample_pointsResp)


DESCRIPTOR._options = None

_SAMPLEPOINTSSERVER = _descriptor.ServiceDescriptor(
  name='SamplePointsServer',
  full_name='sample_points.SamplePointsServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=187,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='All_Sample_points',
    full_name='sample_points.SamplePointsServer.All_Sample_points',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GETALL_SAMPLE_POINTSRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])

_sym_db.RegisterServiceDescriptor(_SAMPLEPOINTSSERVER)

DESCRIPTOR.services_by_name['SamplePointsServer'] = _SAMPLEPOINTSSERVER

# @@protoc_insertion_point(module_scope)
